[[redirects]]
  from = "/api/*"
  to = "https://quizzical-kare-e3193e.netlify.com/"
  status = 200
  force = true
  conditions = {Role = ["admin", "cms"]}
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"